version: '3.3'

services:
  varnish:
    image: varnish:7.3
    container_name: varnish
    volumes:
      - "./docker/varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "8081:80"
    depends_on:
      - "app"

  app:
    depends_on:
      - app_db
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: wp-graphql-smart-cache:latest-wp${WP_VERSION}-php${PHP_VERSION}
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-smart-cache'
    env_file:
      - .env.dist
    environment:
      USING_XDEBUG: ${USING_XDEBUG:-}
    ports:
      - '8091:80'

  app_db:
    image: mariadb:10.11
    env_file:
      - .env.dist
    ports:
      - '3306'

  testing:
    depends_on:
      - testing_db
    build:
      context: .
      dockerfile: docker/Dockerfile.testing
    image: wp-graphql-smart-cache-testing:latest-wp${WP_VERSION}-php${PHP_VERSION}
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-smart-cache'
    env_file:
      - .env.testing
    environment:
      WP_URL: http://localhost
      USING_XDEBUG: ${USING_XDEBUG:-}

  testing_db:
    image: mariadb:10.11
    env_file:
      - .env.testing
    ports:
      - '3306'
